# Generated by Django 4.1.4 on 2023-03-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="product_files/"),
        ),
    ]
